### ISSUE TITLE
Feature: Natural list

### ISSUE THREAD

**Issue by akshaybabloo** [python-humanize/humanize#103]
I was wondering if we can have a feature that converts a list to a sentence; example - `["dog", "cat", "mouse"]` and convert it to `Dog, Cat and Mouse`.

I can add this feature if you are up for it. Thanks.

**Comment by hugovk** [comment]
Thanks for the suggestion.

That would be useful, and could be implemented along the lines of https://stackoverflow.com/a/32008908/724176

Let's leave the capitalisation out. 

We could also have an input parameter to choose whether to use Oxford commas (a, b, and c) or AP style (a, b and c). And maybe to also change the "and" to "or" or something else. But let's defer those for followups if there's actual demand for it.

**Comment by akshaybabloo** [comment]
Yeah that's what I have been using so far.
