### ISSUE TITLE
intword with negative numbers

### ISSUE THREAD

**Issue by maxrioux100** [python-humanize/humanize#12]
### What did you do?

```python
import humanize
print(humanize.intword(-1000000000))
```

### What did you expect to happen?

```
-1.0 billion
```

### What actually happened?

```
-1000000000
```

### What versions are you using?

* OS: Windows 10
* Python: 3.10.4
* Humanize: 3.14

**Comment by hugovk** [comment]
Thanks, I'd be open to a PR.

**Comment by maxrioux100** [comment]
`import humanize
def with_negative(number):
    negative = number < 0
    if negative : number * -1
    word = humanize.intword(number)
    if negative : word = '-' + word
    return word
print(with_negative(-1000000000))`

Something like that (I wrote it in the browser without testing so it may not have some typos)

**Comment by carterbox** [comment]
By opening a PR, hugovk means [open a pull-request](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/about-pull-requests) with some changes to [the source code of humanize](https://github.com/python-humanize/humanize/blob/410b51d63a785b0cb96a52f55aed1256d5244c6d/src/humanize/number.py#L195), not writing a new function that wraps around the existing humanize API.

**Comment by maxrioux100** [comment]
```python
def intword(value, format="%.1f"):
    """Converts a large integer to a friendly text representation.
    Works best for numbers over 1 million. For example, 1_000_000 becomes "1.0 million",
    1200000 becomes "1.2 million" and "1_200_000_000" becomes "1.2 billion". Supports up
    to decillion (33 digits) and googol (100 digits).
    Examples:
        ```pycon
        >>> intword("100")
        '100'
        >>> intword("12400")
        '12.4 thousand'
        >>> intword("1000000")
        '1.0 million'
        >>> intword(1_200_000_000)
        '1.2 billion'
        >>> intword(8100000000000000000000000000000000)
        '8.1 decillion'
        >>> intword(None) is None
        True
        >>> intword("1234000", "%0.3f")
        '1.234 million'
        ```
    Args:
        value (int, float, str): Integer to convert.
        format (str): To change the number of decimal or general format of the number
            portion.
    Returns:
        str: Friendly text representation as a string, unless the value passed could not
        be coaxed into an `int`.
    """
    try:
        value = int(value)
    except (TypeError, ValueError):
        return value

    negative = value < 0
    if negative : value *= -1
    
    if value < powers[0]:
        return str(value)
    for ordinal, power in enumerate(powers[1:], 1):
        if value < power:
            chopped = value / float(powers[ordinal - 1])
            if float(format % chopped) == float(10**3):
                chopped = value / float(powers[ordinal])
                singular, plural = human_powers[ordinal]
                return (
                    " ".join([format, _ngettext(singular, plural, math.ceil(chopped))])
                ) % chopped
            else:
                singular, plural = human_powers[ordinal - 1]
                return (
                    " ".join([format, _ngettext(singular, plural, math.ceil(chopped))])
                ) % chopped

     if negative : value = f'-{value}'

    return str(value)
```
It was just to help you. Here is a better version. Not on my computer so I don't have access to git
