### ISSUE TITLE
TypeError: can't subtract offset-naive and offset-aware datetimes

### ISSUE THREAD

**Issue by ErikKalkoken** [python-humanize/humanize#122]
### What did you do?

I wanted to calculate naturaltime between two timezone aware datatimes.

### What did you expect to happen?

Get a string the with naturaltime between those datetimes.

### What actually happened?

A TypeError exception was raised:

```sh
Traceback (most recent call last):
  File "/home/erik/python/projects/aa-dev/aa-memberaudit/temp/humanize_bug.py", line 8, in <module>
    result = humanize.naturaltime(same_dt, when=my_now)
  File "/home/erik/python/projects/aa-dev/venv/lib/python3.10/site-packages/humanize/time.py", line 253, in naturaltime
    date, delta = _date_and_delta(value, now=now)
  File "/home/erik/python/projects/aa-dev/venv/lib/python3.10/site-packages/humanize/time.py", line 76, in _date_and_delta
    delta = now - value
TypeError: can't subtract offset-naive and offset-aware datetimes
```

### What versions are you using?

* OS: Ubuntu 22.04.2
* Python:  3.10
* Humanize: 4.7.0

Please include **code** that reproduces the issue.

The [best reproductions](https://stackoverflow.com/help/minimal-reproducible-example) are [self-contained scripts](https://ericlippert.com/2014/03/05/how-to-debug-small-programs/) with minimal dependencies.

```python
import datetime as dt

import humanize

my_now = dt.datetime.now(tz=dt.timezone.utc)
same_dt = my_now - dt.timedelta(days=3, hours=1)

result = humanize.naturaltime(same_dt, when=my_now)
```

### Additional information

This bug was introduced with 4.7, the code works fine with 4.6.

As a workaround one could remove the `when=my_now` part (a workaround to get it the function working with aware datetimes), but then it no longer works with humanize < 4.7, which would make 4.7 a breaking change. And it would also not work for when `when` is used in any other way.

**Comment by sshaikh** [comment]
Do we know what the expected release/date is for this fix? I'm trying to decide if I should release pinning to 4.6 or wait.

**Comment by hugovk** [comment]
I've not had chance to check the PR yet, and no-one else has reviewed either. Would you be able to check it? I could probably release next week if all is well. Thanks!

**Comment by shadchin** [comment]
I use patch from #123 , it works fine
