### ISSUE TITLE
Currency value in words

### ISSUE THREAD

**Issue by nsrshishir** [python-humanize/humanize#132]
### What did you do?
Wanted to print the Sale order total say "78568.1257" in Human readable string.
### What did you expect to happen?
output like "Seventy eight thousand five hundred sixty eight dollar and thirteen cents"
### What actually happened?
78.57 thousand

### What versions are you using?
4.7.0

* OS: Ubuntu 22.04
* Python: 3.10
* Humanize: 4.7.0

```python
import humanize
print(humanize.intword(78568.1257, format='%.2f'))

```

**Comment by hugovk** [comment]
You can do something like this using https://pypi.org/project/inflect/

```python
import math

import inflect  # pip install inflect

value = 78568.1257
p = inflect.engine()

cents, dollars = math.modf(value)

dollars = p.number_to_words(round(dollars))
cents = p.number_to_words(round(cents * 100))

print(f"{dollars} dollars and {cents} cents")
```
```
seventy-eight thousand, five hundred and sixty-eight dollars and thirteen cents
```

**Comment by nsrshishir** [comment]
Thanks Python-Humanize/Humanize. Appreciate it.

Best Regards,
Md. Niaj Shahriar Shishir
Software Engineer and Server Specialist,
Metamorphosis Ltd,
Dhaka, Bangladesh.
Cell: 01827512928
