### ISSUE TITLE
`humanize.intword` Unwanted decimal value

### ISSUE THREAD

**Issue by Nzii3** [python-humanize/humanize#136]
### What did you do?
Tried to have `humanize` humanize the number `1,000` to a number-word.
### What did you expect to happen?
I expected to get a number that doesn’t have a decimal value when the decimal is 0.
### What actually happened?
I got a `1.0 thousand` when I don’t want that 0 decimal place.
### What versions are you using?

* OS: Not self hosting
* Python: latest
* Humanize: latest

Please include **code** that reproduces the issue.

The [best reproductions](https://stackoverflow.com/help/minimal-reproducible-example) are [self-contained scripts](https://ericlippert.com/2014/03/05/how-to-debug-small-programs/) with minimal dependencies.

```python
print(humanize.intword(1000))
```

**Comment by hugovk** [comment]
Does changing the `format` parameter help?

https://humanize.readthedocs.io/en/latest/number/#humanize.number.intword

**Comment by Nzii3** [comment]
@hugovk No because I only want it to do decimals when the decimal number isn’t 0.

**Comment by hugovk** [comment]
Yeah, I guessed as much :)

As a workaround, you can do something like:

```python
humanize.intword(1000).replace(".0 ", " ")
```

**Comment by Nzii3** [comment]
I guess that works, but it would be nice to have a positional argument for it in the function.

**Comment by byron-hawkins** [comment]
You can use `format = "%g"` as a positional parameter to automatically eliminate trailing zeros in the significand. It would actually be nice to have this as a default, since the whole point of humanize is to avoid robotic equivocations that nobody would ever write with a pencil.
