### ISSUE TITLE
naturaldelta with negative seconds loses precision and doesn't match naturaltime

### ISSUE THREAD

**Issue by Dapid** [python-humanize/humanize#18]
### What did you do?
I passed a small negative integer value to `naturaldelta`, it reports "a day".

### What did you expect to happen?
I expect `naturaldelta` to roughly match `naturaltime`. Else, if negative values are not supported, it should be documented.

### What actually happened?
```python
import humanize

print(humanize.naturaldelta(-1))
print(humanize.naturaltime(-1))
```
shows:
```
a day
a second ago
```

### What versions are you using?

* OS: `Linux LCARS2 5.17.4-200.fc35.x86_64 #1 SMP PREEMPT Wed Apr 20 15:37:53 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux`
* Python: 3.9.12
* Humanize: 4.1.0

**Comment by carterbox** [comment]
```
>>> dt.timedelta(seconds=-1)
datetime.timedelta(days=-1, seconds=86399)
>>> dt.timedelta(seconds=1)
datetime.timedelta(seconds=1)
```
I also didn't expect this behavior, but `humanize.naturaldelta()` matches the behavior of `datetime.timedelta()`.

**Comment by carterbox** [comment]
One solution could be to call `abs()` on the `value` parameter since a delta is neither negative or positive. `abs()` also works on `dt.timedeltas`.
