### ISSUE TITLE
Suggestion/query: is there an opposite of humanize?

### ISSUE THREAD

**Issue by danj2k** [python-humanize/humanize#187]
This module is great for converting file sizes to human readable numbers. But what if I want to go the other way? What if I want to allow my users to specify human-readable units in my configuration file? I need some way to read that back in to machine-readable format.

Is there an opposite of humanize?

**Comment by hugovk** [comment]
Please see https://github.com/jmoiron/humanize/issues/173.

**Comment by chapmanjacobd** [comment]
@danj2k `dateutil` is pretty popular dependency for date parsing. It works pretty well. I made a CLI for it and used that recently to parse URL paths / file names into dates:

- https://github.com/chapmanjacobd/library/blob/main/xklb/text/dates.py
- https://github.com/chapmanjacobd/us_visa_statistics/blob/f6017ab82483ab9eb0a232e2d6df7cd83ed9019e/.github/workflows/immigrant.yaml#L30

Human size to bytes is pretty simple too:

- https://github.com/chapmanjacobd/library/blob/44d0bee3d7ee30cbbf88fe8421740c2f3afd09d5/xklb/utils/nums.py#L72
- https://github.com/chapmanjacobd/computer/blob/main/bin/human_size_sum.py
