### ISSUE TITLE
Translation for thousands is wrong in French

### ISSUE THREAD

**Issue by enlivn** [python-humanize/humanize#191]
### What did you do?
```python
>>> import humanize as h
>>> print(h.__version__)
4.8.0
>>> h.i18n.activate('fr')
<gettext.GNUTranslations object at 0x1033a9c30>
>>> h.intword(22382)
'22.4 thousand'
```

### What did you expect to happen?
`thousand` should be `mille` or `milles` for plural in French

### What actually happened?
prints `thousand`

### What versions are you using?

* OS: MacOS Sonoma 14.5
* Python: 3.10.11
* Humanize: 4.8.0

See code snippet at start of issue.

**Comment by hugovk** [comment]
Looks like we're missing the translation here:
https://github.com/python-humanize/humanize/blob/2a141c7f5b51e09c8c4d6e00903101932aef4d11/src/humanize/locale/fr_FR/LC_MESSAGES/humanize.po#L122-L126

Would you like to contribute a PR?

**Comment by enlivn** [comment]
> Looks like we're missing the translation here:
> 
> https://github.com/python-humanize/humanize/blob/2a141c7f5b51e09c8c4d6e00903101932aef4d11/src/humanize/locale/fr_FR/LC_MESSAGES/humanize.po#L122-L126
> 
> Would you like to contribute a PR?

sure, I can look into it.

**Comment by enlivn** [comment]
@hugovk just put up #192. Thanks for your quick response.
