### ISSUE TITLE
Feature Request: a function to humanize actual time (e.g. '7:30AM')

### ISSUE THREAD

**Issue by Nzii3** [python-humanize/humanize#60]
Kind of self explanatory, could be something like `humanize.precisetime(float)`

**Comment by hugovk** [comment]
Please could you explain in more details? 

Examples help.

What sort of inputs would you give and what sort of outputs would you expect?

**Comment by carterbox** [comment]
The built-in datetime module already provides precise time descriptions in a format of your choosing.

https://docs.python.org/3/library/time.html#time.strftime

**Comment by Nzii3** [comment]
@carterbox Sometimes datetime for me is not accurate when trying to get it in UTC because my os time is Europe I think because I share a VPS with a friend from Europe. Therefore, I can't get accurate UTC time.
