### ISSUE TITLE
Test on 3.11 instead of 3.11-dev

### ISSUE THREAD

**Issue by hugovk** [python-humanize/humanize#67]
Python 3.11.0 final [is now out](https://discuss.python.org/t/python-3-11-0-final-is-now-available/20291?u=hugovk)!

Let's replace `"3.11-dev"` with `3.11` in `.github/workflows/test.yml` so we're testing on the new version.

**Comment by zafar-hussain** [comment]
Hi @hugovk,

Please assign this issue to me,

cheers
