### ISSUE TITLE
German localization for intword missing thousand, and some plurals

### ISSUE THREAD

**Issue by NavisGames** [python-humanize/humanize#88]
### What did you do?
I am using humanize.intword to get a number to be a intword in german.

### What did you expect to happen?
The Code should print something like `1.2 Millionen` or `2 Tausend`

### What actually happened?
Everytime, it prints 1.2 Million, on other numbers that are in the thousands it doesnt print "tausend" it prints "thousand" like in the english.

A few Months or Weeks ago everything worked fine in german. i dont know why it doesnt work anymore

### What versions are you using?

* OS: Windows 10
* Python: 3.10
* Humanize: 4.40

Please include **code** that reproduces the issue.

The [best reproductions](https://stackoverflow.com/help/minimal-reproducible-example) are [self-contained scripts](https://ericlippert.com/2014/03/05/how-to-debug-small-programs/) with minimal dependencies.

```py
import humanize
_t = humanize.i18n.activate("de_DE")

def intword(num):
    num = humanize.intword(num)
    num = num.replace(".0", "")
    return num

print(intword(1250000) # 1.2 Million should be 1.2 Millionen
print(intword(2000) # 2 thousand should be 2 Tausend
```

**Comment by hugovk** [comment]
Which version were you using before?

Does it work with 4.3.0 or older?

**Comment by NavisGames** [comment]
i dont excactly remember.. imma install a older version and check out.

**Comment by NavisGames** [comment]
i checked, over a million is in german, in million and thousand its in english.

**Comment by NavisGames** [comment]
like when it gets to a billion in english, it goes to `Milliarde` which is correct.

**Comment by NavisGames** [comment]
![image](https://user-images.githubusercontent.com/83245135/211204501-8cf10fe4-aa38-4c67-a0a2-99b2bf1e5f97.png)

**Comment by NavisGames** [comment]
i have made a pull request for the localisation for german :)
