### ISSUE TITLE
Wrong italian translation

### ISSUE THREAD

**Issue by abidibo** [python-humanize/humanize#94]
Italian translation of last phrase is missing:

https://github.com/python-humanize/humanize/blob/main/src/humanize/locale/it_IT/LC_MESSAGES/humanize.po#L364

it should be

```
#: src/humanize/time.py:534
#, python-format
msgid "%s and %s"
msgstr "%s e %s"
```

**Comment by hugovk** [comment]
Thanks, please see PR #95.
